name: Fetch Conjur Secret
 
on:
  push:
    branches: [ main ]
 
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Install curl and jq
      run: sudo apt-get update && sudo apt-get install -y curl jq
 
    - name: Authenticate to Conjur and retrieve secret
      env:
        CONJUR_ACCOUNT: conjur
        CONJUR_URL: ${{ secrets.CONJUR_URL }}
        CONJUR_AUTHN_LOGIN: ${{ secrets.CONJUR_AUTHN_LOGIN }}
        $CONJUR_AUTHN_API_KEY: ${{ secrets.CONJUR_AUTHN_API_KEY }}
      run: |
        set -e
 
        echo "=============================="
        echo "Logging into Conjur..."
        echo "Account: $CONJUR_ACCOUNT"
        echo "Appliance URL: $CONJUR_APPLIANCE_URL"
        echo "Authn Login: $CONJUR_AUTHN_LOGIN"
        echo "=============================="
 
        echo "Authenticating..."
 
        FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
        echo "Calling authn URL: $FULL_AUTHN_URL"
 
        # RESPONSE=$(curl -i -s -w "\n%{http_code}" \
        #   --request POST \
        #   --data "$CONJUR_AUTHN_API_KEY" \
        #   "$FULL_AUTHN_URL")
         AUTHN_TOKEN=$(curl -s -k --request POST \
         --data "$CONJUR_AUTHN_API_KEY" \
         "$CONJUR_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate" \
         | base64 | tr -d '\r\n')
 
        echo "Full /authenticate response:"
        echo "$AUTHN_TOKEN"

        echo "Authentication successful"
        echo "=============================="
 
        echo "Fetching secret...."
 
       
         SECRET=$(curl -s -k --header "Authorization: Token token=\"$AUTHN_TOKEN\"" \
        "$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/data%2Fvault%2Fconjurtest%2Fconjurtest%2Faddress")
 
        SECRET_VALUE=$(echo "$SECRET" | head -n1)
       
        
        echo "Retrieved secret: $SECRET_VALUE"
